# SCREEN
SCREEN_CAPTION = "pyng"
SCREEN_MODE = SCREEN_WIDTH, SCREEN_HEIGHT = 450, 650
SCREEN_MOUSE_VISIBLE = False

# PADDLE
PADDLE_SIZE = PADDLE_WIDTH, PADDLE_HEIGHT = 50, 10
PADDLE_COLORNAME = "white"

# BALL
BALL_SIZE = (10, 10)
BALL_START_POS = (220, 320)
BALL_COLORNAME = "grey"

# BACKGROUND
BACKGROUND_COLORNAME = "black"
BACKGROUND_LINE_COLORNAME = "white"
